### ISSUE TITLE
Дублирование входных данных в примерах

### ISSUE THREAD

**Issue by Calrission** [Alexandre77777/python_programming#1]
В [Модуле 3 "Строки" в задании №3](https://github.com/Alexandre77777/python_programming/blob/main/1.%20%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C%20%E2%84%962.%20%D0%A7%D0%B8%D1%81%D0%BB%D0%B0.ipynb) в качестве примера ввода 2 и 3 указанно одно и тоже - "office", хотя примеры вывода для них различны.

![Без названия](https://github.com/Alexandre77777/python_programming/assets/95771802/32057a78-9d0f-45e0-93f6-543afc9e038b)

**Comment by Alexandre77777** [comment]
👌🏻
