### ISSUE TITLE
Неправильный пример вывода

### ISSUE THREAD

**Issue by Calrission** [Alexandre77777/python_programming#2]
В [6 модуле в 8 задании ](https://github.com/Alexandre77777/python_programming/blob/main/1.%20%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C%20%E2%84%966.%20%D0%9F%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8.ipynb)сказано, что на второй строке вывода необходимо вывести последний символ строки из ввода. В примере в качестве строки ввода указано "Abrakadabra", в котором последний символ "a", но в примере вывода указанно "r".

![image](https://github.com/Alexandre77777/python_programming/assets/95771802/60a7a2ff-ab34-4313-bb85-a6c7a5c12761)
![Без названия (1)](https://github.com/Alexandre77777/python_programming/assets/95771802/c8e861b2-22f8-4103-a117-26599a06e5b1)

**Comment by Alexandre77777** [comment]
✅
